### ISSUE TITLE
Partial parameters

### ISSUE THREAD

**Issue by SerenadeX** [XaminProject/handlebars.php#116]
So when I load in a hbs file that uses a partial

```hbs
<div class="topics-search">
  <input type="text" class="topics-search__text-input">
  <button class="topics-search__submit">
    {{> icon iconClass=search}}
  </button>
</div>
```

I get the following error

```
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'variable name is invalid' in includes/handlebars.php/src/Handlebars/Context.php:301 
Stack trace: 
#0 includes/handlebars.php/src/Handlebars/Context.php(237): Handlebars\Context->_splitVariableName('iconClass='sear...') 
#1 includes/handlebars.php/src/Handlebars/Template.php(503): Handlebars\Context->get('iconClass='sear...') 
#2 includes/handlebars.php/src/Handlebars/Template.php(241): Handlebars\Template->_partial(Object(Handlebars\Context), Array) 
#3 includes/handlebars.php/src/Handlebars/Template.php(180): Handlebars\Template->_renderInternal(Array, Object(Handlebars\Context)) 
#4 includes/handlebars.php/src/Handlebars/Handlebars.php(184): Handlebars\Template->render(A in includes/handlebars.php/src/Handlebars/Context.php on line 301
```

I don't know why my partial variable is getting rejected or what is wrong with my variable name.  There isn't much documentation on this either.  I am not sure if there is a bug breaking this, or if I am just doing it wrong.

**Comment by majortom731** [comment]
Maybe what you mean is `iconClass="search"`, with quotes?

**Comment by SerenadeX** [comment]
I've done it both with and without quotes and I get the same result

**Comment by JustBlackBird** [comment]
It seems to be a bug. I've made a js fiddle that illustrates Handlebars.js behavior: http://jsfiddle.net/q9emfa80/

**Comment by SerenadeX** [comment]
Good I'm glad I'm not crazy 😁

**Comment by SerenadeX** [comment]
Has anyone made any progress on this?

**Comment by thormeier** [comment]
Fixed with https://github.com/XaminProject/handlebars.php/pull/124 I guess

**Comment by JustBlackBird** [comment]
It seems that the problem is fixed with #124. @SerenadeX could you confirm it?

**Comment by SerenadeX** [comment]
Confirmed.  Works like a charm 👍🏻

**Comment by JustBlackBird** [comment]
Good to hear! Thank you @thormeier for the fix!

**Comment by thormeier** [comment]
Thanks @SerenadeX for testing. @JustBlackBird You're welcome! Is it possible to create a version tag, for instance `v0.10.1` for that?
