### ISSUE TITLE
Please remove "var_export"!

### ISSUE THREAD

**Issue by Zemistr** [XaminProject/handlebars.php#129]
Hi,
pleeeeeeeease remove "var_export" from \Handlebars\Context::_findVariableInContext !

When I use bigger data, whole server is down...

**Comment by fzerorubigd** [comment]
@Zemistr thank you for your report. 
@JustBlackBird I think the only one is https://github.com/XaminProject/handlebars.php/blob/master/src/Handlebars/Context.php#L291and there is no need to keep it.

**Comment by JustBlackBird** [comment]
@Zemistr thanks for the report, but please, don't use such titles anymore!

@fzerorubigd you're right! `var_export` is not needed there. Variable name should be added to the exception instead of the context. I've done so in #130, could you review it?

**Comment by fzerorubigd** [comment]
@JustBlackBird Thank you, It's done.

**Comment by Zemistr** [comment]
@JustBlackBird: YW and sorry :sweat_smile: 

Many, many thanks! :kissing:

**Comment by Zemistr** [comment]
bushmanshop@zemistr.eu
