### ISSUE TITLE
Usage of reserved names for PHP7

### ISSUE THREAD

**Issue by camsjams** [XaminProject/handlebars.php#133]
This library doesn't work in PHP 7 = Cannot use Handlebars\String as String because 'String' is a special class name.

**Comment by JustBlackBird** [comment]
We could replace `\Handlebars\String` with `\Handlebars\UnsafeString` to play nice with PHP7 but it can break backward compatibility. What do you think @fzerorubigd ?

**Comment by everplays** [comment]
We can just check the php version and load a different class. And to avoid maintaining duplicate code, either they can both inherit from one class or we can use traits.

**Comment by everplays** [comment]
Even simpler: We can have `\Handlebars\UnsafeString` as main implementation just like you suggested and extend `\Handlebars\String` from it (making it deprecated). Nothing else is required for this as php 7 users will stick to `\Handlebars\UnsafeString` and others will continue using `\Handlebars\String`.

**Comment by JustBlackBird** [comment]
@everplays the second option (about inheritance) you've proposed could be the way to go. I'll try to implement a PR for that soon.

**Comment by JustBlackBird** [comment]
Actually the situation is more complicated than I thought before. [Here](https://github.com/XaminProject/handlebars.php/blob/master/src/Handlebars/Template.php#L384) `\Handlebars\String` is used to wrap template contents. Do we need one more string class (lets say `\Handlebars\TemplateString`) for such usage?

**Comment by everplays** [comment]
@JustBlackBird this part should be checked with an `if` statement. If the version is 7, only check against `UnsafeString`. Otherwise, both `UnsafeString` and `String`.

**Comment by mfeltscher** [comment]
Could you please release a new version containing #135 ?

Thanks!

**Comment by everplays** [comment]
I just tagged `v0.10.3`. Enjoy.

**Comment by mfeltscher** [comment]
Thank you! PHP 7 here we come! :)
