### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by Desertsnowman** [XaminProject/handlebars.php#138]
Hi there,

experiencing an issue with PHP 7 : 
```
Fatal error:  Cannot use Handlebars\String as String because 'String' is a special class name in ....src/Handlebars/Loader/StringLoader.php on line 22 
```
Any idea if this will be addressed?

**Comment by mfeltscher** [comment]
Hi @Desertsnowman 

Version 0.10.3 is fully PHP 7 compatible so you just have to upgrade to that version.


Moreno

**Comment by Desertsnowman** [comment]
:facepalm: Thanks ;)
