### ISSUE TITLE
How to not proccess (escape) markup?

### ISSUE THREAD

**Issue by jcubic** [XaminProject/handlebars.php#149]
Is it possible to stop processing of handlerbars markup for a moment? something like:

```html
{{#escape}}
<script type="type/x-handlebars">
{{#each user in controller}}
   {{user.name}}
{{/each}}
</script>
{{/escape}}
```
and have javascript handlebars and not php one. if not is it possible to create a helper that will do this?

**Comment by everplays** [comment]
Have you tried just returning the raw text from your `escape` helper as `SafeString`? It should do the job. I am not 100% sure though.

**Comment by jcubic** [comment]
4 argrment to helper is source, to create escape helper I just return source and it work.
