### ISSUE TITLE
Handlebars don't show error on undefined helper

### ISSUE THREAD

**Issue by jcubic** [XaminProject/handlebars.php#150]
I've used this code:
```php
$engine = new Handlebars();

echo $engine->render("{{#each foo}}{{this}}{{/each}}{{#escape}}{{foo}}{{/escape}}", array(
    'foo' => array(
        '1', '2', '3', '4'
    )
));
```

and handlebars don't show error that escape is not defined it just ignore it.

**Comment by JustBlackBird** [comment]
It's because of Mustache syntax fallback. In a Mustache template 

```mustache
{{#foo}}
    {{bar}}
{{/foo}}
```

the output will depend on what `foo` is: hash, empty value or lambda. The details could be found in [Mustache docs](https://mustache.github.io/mustache.5.html#Sections).

In other words, I don't think it's a kind of bug.
