### ISSUE TITLE
Get current helper content as string or tree

### ISSUE THREAD

**Issue by jcubic** [XaminProject/handlebars.php#151]
I want to impement escape helper, for this to work I need to have access to text that's inside helper.

I can call `$template->getTree();` method to get the whole tree of the template but not the current helper content tree.

Is there a way to get the string that's inside block helper?

**Comment by everplays** [comment]
Have a look here: https://github.com/XaminProject/handlebars.php/blob/198faa48d620807541dacf84fe03a785692f1203/tests/Xamin/HandlebarsTest.php#L427

You get a `Template` instance which has `getSource` method.

**Comment by jcubic** [comment]
getSource return whole template and I want to get the current helper content.

**Comment by fzerorubigd** [comment]
I think the source parameter is passed to helpers (third one if i can remmember correctly)

**Comment by jcubic** [comment]
Yes this work, thanks:

```php
$engine->addHelper('escape', function ($template, $context, $arg, $source) {
    return $source;
});
```
