### ISSUE TITLE
How to use @last in #each

### ISSUE THREAD

**Issue by jcubic** [XaminProject/handlebars.php#152]
I want to have something like this:

```
{{#each items}}
{{this}}{{#if !@last}}, {{/if}}
{{/each}}
```
to display comma after all items except the last one. How can I do this?

**Comment by JustBlackBird** [comment]
There is built-in `{{#unless}}` helper that solves your problem.

{{#each items}}
  {{this}}{{#unless @last}}, {{/unless}}
{{/each}}
