### ISSUE TITLE
A way to use arbitrary text as arguments in custom helper

### ISSUE THREAD

**Issue by jcubic** [XaminProject/handlebars.php#153]
I want to implement my own if helper that will have arbitrary expressions like this:
```
{{#if foo =~ /bar/}}
    foo is bar
{{/if}}
```
but this throw `InvalidArgumentException: Malformed arguments string`, the solution is to use quotes for the whole thing but it would be nice if the lib will allow to use any text.

**Comment by JustBlackBird** [comment]
There is only limited set of things that could be arguments. As far as I remember neither `=~` nor `/bar/` are not valid arguments. So the only option is to strings like `"=~"` and `"/bar/"`.

Also, I don't think that rewriting of one of built-in helpers is a good idea.

**Comment by JustBlackBird** [comment]
Also, you could implement a helper like:

```handlebars
{{#ifMatchRegExp value pattern}}
  Yep, it matches.
{{/ifMatchRegExp}}
```

**Comment by jcubic** [comment]
I've fixed this by adding quotes before calling render.
