### ISSUE TITLE
Variables are searched only in current context not in context stack

### ISSUE THREAD

**Issue by jcubic** [XaminProject/handlebars.php#155]
I have helper `#sql` that work like `#each` but fetch data from databse and I have template like this:
```
{{#sql "SELECT id FROM test"}}
    {{#sql "SELECT content FROM test WHERE id = $id"}}
        {{id}}: {{content}}
    {{/sql}}
{{/sql}}
```
the id from second `sql` should be the one from first `sql`, but it return nothing and you get only list of `content`. For `$variables` I've created this code:
```php
    function get_context_var($context, $var) {
        $stack = array();
        while (true) {
            try {
                $value = $context->get($var, true);
                //restore the context
                while (end($stack)) {
                    $context->push(array_pop($stack));
                }
                return $value;
            } catch(Exception $e) {
                // save context for restoration
                array_push($stack, $context->pop());
                if (!$context->last()) {
                    throw new Exception("Can't find variable $var");
                }
            }
        }
    }
```
I throw exception because otherwise I will get error in sql.

**Comment by JustBlackBird** [comment]
> the id from second sql should be the one from first sql, but it return nothing and you get only list of content.

No it should not. There is no context inheritance neither in Handlebars.js nor in Handlebars.php. Use constructions like `{{../id}}` to get your case work.
