### ISSUE TITLE
Could you make a release tag?

### ISSUE THREAD

**Issue by ivantcholakov** [XaminProject/handlebars.php#165]
The last release is v0.10.3 which is more than a year ago. Could you make now a new release for the PHP 5.3 version?

I don't prefer to link to dev-master, because I commit Composer's vendor folder (that is ok in my case). But when dev-master is used the committed folder handlebars.php gets empty. On the other hand, the last (stable?) release seems to me quite outdated.

**Comment by everplays** [comment]
There you go, current HEAD of master is tagged as `v.0.10.4`.

**Comment by ivantcholakov** [comment]
Thank you very much. :-)
