### ISSUE TITLE
How can I use this JS template in a page rendered by handlebars.php

### ISSUE THREAD

**Issue by funkytaco** [XaminProject/handlebars.php#166]
How can I use this JS template in a page rendered by handlebars.php
```
<script id="example-template" type="text/x-handlebars-template">
{{phpRendersThisInsteadOfJs}}
<!-- I want JS Handlebars to render and have Handlebars.PHP rendering on backend to ignore it //-->
</script>
```

I have one page which I must use JSON calls on, but I use handlebars.php, and it looks like it's parsing the {{mustachified}} variables.

 I'd like to use handlebarsJs for the front-end on this page. How can I prevent the PHP Handlebars from rendering this?

Id rather not render my HTML via javascript echo if at all possible. Thanks!

**Comment by everplays** [comment]
check #149.

**Comment by funkytaco** [comment]
Ez pz. Thanks @everplays.
